language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
